name: 构建plum内核

on:
  watch:
    types: [started]

jobs:
  KneipKernel:
    runs-on: ubuntu-latest
    steps:
      - name: 环境准备
        run: |
          sudo apt update -y
          sudo apt-get install -y zipalign openssl ccache bc bash git-core gnupg build-essential zip curl make automake autogen autoconf autotools-dev libtool shtool python  m4 gcc libtool zlib1g-dev flex libssl-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi python2
      - name: 拉取源代码和工具链
        run: |
          git clone https://github.com/linfeng122/Auto-kernel-build.git --depth=1
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1
          mv linux-x86/clang-r416183c clang
          rm -rf linux-x86
          git clone --depth=1 https://github.com/linfeng122/Anykernel3.git -b main
      - name: 构建内核
        run: |
          CLANG_DIR=../clang
          export KBUILD_BUILD_USER="linfeng122"
          export KBUILD_BUILD_HOST="Workspace"
          args="O=../out ARCH=arm64 CC=${CLANG_DIR}/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LD=${CLANG_DIR}/bin/ld.lld"
          cd Xiaomi_Kernel_OpenSource-cmi-r-oss

          make ${args} vendor/cmi_user_defconfig
          make -j$(nproc --all) ${args}
      - name: 上传内核
        run: |
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          cd AnyKernel3
          VERSION="$(cat ../Xiaomi_Kernel_OpenSource-cmi-r-oss/arch/arm64/configs/alioth_defconfig | grep "CONFIG_LOCALVERSION\=" | sed -r 's/.*"(.+)".*/\1/' | sed 's/^.//')"
          7z a -mx9 ${VERSION}.zip *
          zipalign -v 4 ${VERSION}.zip ../${VERSION}_cmi.zip
          cd ..
          curl -sL https://git.io/file-transfer | bash -s beta
          ./transfer wet ${VERSION}_cmi.zip
